# Generated by Django 3.1.2 on 2020-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user_value_ave',
            field=models.IntegerField(null=True),
        ),
    ]
