# Generated by Django 3.1.2 on 2020-11-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user_value_ave',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='anime_genre',
            field=models.CharField(choices=[('SF', 'SF'), ('ギャグ', 'ギャグ'), ('恋愛', '恋愛'), ('青春', '青春'), ('ホラー', 'ホラー'), ('日常', '日常'), ('ミステリー', 'ミステリー'), ('バトル', 'バトル')], max_length=15),
        ),
    ]
