# Generated by Django 3.1.2 on 2020-11-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_reviewmodel_user_value_ave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='user_value_ave',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
    ]
