# Generated by Django 3.1.2 on 2020-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_access_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='SF_sum_value2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='SF_sum_value3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='SF_sum_value4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='SF_sum_value5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
